#!/bin/sh
(
	echo "/***---NATIVES: PROTOTYPES---***/"
	echo "/***AUTOGENERATED DO NOT MANUALLY EDIT***/"
	echo
	egrep '^NATIVE[(]' snailNativeImpl.h | sed -e 's/) {/);/' | sort
	echo
	echo "/***AUTOGENERATED DO NOT MANUALLY EDIT***/"
) > snailNativeProtos.h

(
	echo "/***---DOS NATIVES: PROTOTYPES---***/"
	echo "/***AUTOGENERATED DO NOT MANUALLY EDIT***/"
	echo
	egrep '^NATIVE[(]' snailNativeImplDOS.h | sed -e 's/) {/);/' | sort
	echo
	echo "/***AUTOGENERATED DO NOT MANUALLY EDIT***/"
) > snailNativeProtosDOS.h
