/***---DOS NATIVES: PROTOTYPES---***/
/***AUTOGENERATED DO NOT MANUALLY EDIT***/

NATIVE(dos_int86,2);
NATIVE(dos_mem_alloc,1);
NATIVE(dos_mem_fixed,2);
NATIVE(dos_mem_peek,2);

/***AUTOGENERATED DO NOT MANUALLY EDIT***/
