/***---NATIVES: PROTOTYPES---***/
/***AUTOGENERATED DO NOT MANUALLY EDIT***/

NATIVE(add, VARIADIC);
NATIVE(div, VARIADIC);
NATIVE(eq, 2);
NATIVE(error, 1);
NATIVE(gt, 2);
NATIVE(gte, 2);
NATIVE(if,VARIADIC);
NATIVE(info_cmds, 0);
NATIVE(info_cmds_count, 0);
NATIVE(info_vars, 0);
NATIVE(list, VARIADIC);
NATIVE(list_index, 2);
NATIVE(list_length, 1);
NATIVE(list_sort, 1);
NATIVE(lt, 2);
NATIVE(lte, 2);
NATIVE(mul, VARIADIC);
NATIVE(pass,1);
NATIVE(puts, 1);
NATIVE(puts_nonewline, 1);
NATIVE(repl_prompt_get,0);
NATIVE(repl_prompt_set,1);
NATIVE(set, 2);
NATIVE(string_casecmp, 2);
NATIVE(string_cmp, 2);
NATIVE(string_is_blank, 1);
NATIVE(string_is_bool, 1);
NATIVE(string_is_digits, 1);
NATIVE(string_is_false, 1);
NATIVE(string_is_int, 1);
NATIVE(string_is_true, 1);
NATIVE(string_length, 1);
NATIVE(sub, VARIADIC);
NATIVE(token_classify,1);
NATIVE(token_quote,1);
NATIVE(token_unquote,1);
NATIVE(unsupported_parse_dump,1);
NATIVE(var_del, 1);
NATIVE(var_get, 1);
NATIVE(var_has, 1);

/***AUTOGENERATED DO NOT MANUALLY EDIT***/
